### ISSUE TITLE
Check if the version exists from the API

### ISSUE THREAD

**Issue by SohamTilekar** [AnimMouse/setup-ffmpeg#1]
[Fail](https://github.com/SohamTilekar/vidiopy/actions/runs/8597781364/job/23557190181)
[test.yaml](https://github.com/SohamTilekar/vidiopy/blob/master/.github/workflows/test.yml)

**Comment by SohamTilekar** [comment]
@AnimMouse How?

**Comment by AnimMouse** [comment]
Replace [this](https://github.com/SohamTilekar/vidiopy/blob/a84d49a92c9d1946f005dfff85460cab2ffc797a/.github/workflows/test.yml#L30) with:
```yaml
      - name: Install FFMPEG
        uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: 6.1.1
```

**Comment by SohamTilekar** [comment]
Should I close the Issue, or you are adding a logic if the specific release does not exist yet.

**Comment by AnimMouse** [comment]
I will add the logic, so don't close the issue yet so that I can track this bug.

**Comment by SohamTilekar** [comment]
> Replace [this](https://github.com/SohamTilekar/vidiopy/blob/a84d49a92c9d1946f005dfff85460cab2ffc797a/.github/workflows/test.yml#L30) with:
> 
> ```yaml
>       - name: Install FFMPEG
>         uses: AnimMouse/setup-ffmpeg@v1
>         with:
>           version: 6.1.1
> ```

[Wrong Version](https://github.com/SohamTilekar/vidiopy/actions/runs/8598829762/job/23560455621)

**Comment by AnimMouse** [comment]
Oops, your workflow is actually a matrix that uses multiple OS, macOS requires the patch version, but other OS should not have patch version.
You can use a conditional like this:
```yaml
      - name: Install FFMPEG
        uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: ${{ runner.os == 'macOS' && '6.1.1' || '6.1' }}
```
Or just use the latest master version:
```yaml
      - name: Install FFMPEG
        uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: master
```
